name: vmi_driver_app
description: VMI Driver sensor data collection app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Sensor and location
  sensors_plus: ^4.0.2
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # File handling
  path_provider: ^2.1.1
  
  # Firebase - Changed from Storage to Firestore
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  
  # Background processing (platform specific)
  flutter_background: ^1.2.0
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true